version: "3.9"

services:
  komikgan:
    container_name: komikgan-backend
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7.4
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data: