version: "3.9"

services:
  postgres:
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
  
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
